[package]
name = "pallet-evm-polkavm"
version = "6.0.0-dev"
license = "Apache-2.0"
readme = "README.md"
description = "PolkaVM support for pallet-evm of Frontier Ethereum-compatibility layer for Polkadot."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { workspace = true }
scale-codec = { workspace = true }
scale-info = { workspace = true }
# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true }
# PolkaVM executor
pallet-evm-polkavm-proc-macro = { workspace = true }
pallet-evm-polkavm-uapi = { workspace = true, features = ["scale"] }
polkavm = { version = "0.25.0", default-features = false }

[features]
default = ["std"]
std = [
	"log/std",
	"scale-codec/std",
	"scale-info/std",
	# Substrate
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
	# PolkaVM executor
	"polkavm/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
runtime-benchmarks = []
