[package]
name = "substrate-test-client"
description = "Client testing utilities (polkadot v1.15.0)"
version = "2.0.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
async-trait = { workspace = true }
codec = { workspace = true, default-features = true }
futures = { workspace = true }
sc-client-api.default-features = true
sc-client-api.workspace = true
sc-client-db = { features = ["test-helpers"], workspace = true }
sc-consensus.default-features = true
sc-consensus.workspace = true
sc-executor.default-features = true
sc-executor.workspace = true
sc-offchain.default-features = true
sc-offchain.workspace = true
sc-service = { features = ["test-helpers"], workspace = true }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sp-blockchain.default-features = true
sp-blockchain.workspace = true
sp-consensus.default-features = true
sp-consensus.workspace = true
sp-core.default-features = true
sp-core.workspace = true
sp-keyring.default-features = true
sp-keyring.workspace = true
sp-keystore.default-features = true
sp-keystore.workspace = true
sp-runtime.default-features = true
sp-runtime.workspace = true
sp-state-machine.default-features = true
sp-state-machine.workspace = true
tokio = { features = ["sync"], workspace = true, default-features = true }
