[package]
name = "pallet-evm-polkavm-uapi"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "Exposes all the host functions that a contract can import."

[package.metadata.docs.rs]
features = ["unstable-hostfn"]
targets = ["riscv64imac-unknown-none-elf"]

[dependencies]
bitflags = { workspace = true }
pallet-evm-polkavm-proc-macro = { workspace = true }
scale-codec = { features = ["derive", "max-encoded-len"], optional = true, workspace = true }
scale-info = { features = ["derive"], optional = true, workspace = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
polkavm-derive = { version = "0.25.0" }

[features]
default = ["scale"]
scale = ["dep:scale-codec", "scale-info"]
unstable-hostfn = []
