[package]
name = "pallet-tkf-daosrv"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
frame-support = { workspace = true, default-features = false }
frame-system  = { workspace = true, default-features = false }
scale-codec = { workspace = true, features = ["derive"], default-features = false }
scale-info = { workspace = true, features = ["derive"], default-features = false }
sp-std = { workspace = true, default-features = false }
log = { workspace = true }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "scale-codec/std",
    "scale-info/std",
    "sp-std/std",
    "log/std",
]
