name: Lint

on:
  push:
    branches:
      - master
      - 'polkadot-v**'
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
      - 'polkadot-v**'
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  lint:
    name: Run Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache cargo registry & git sources
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-lint-
            ${{ runner.os }}-cargo-

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Install Rust toolchain
        run: make setup

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check code format
        run: make fmt-check

      - name: Run clippy
        run: make clippy-release
